"""create lists table

Revision ID: b1a204d9dca2
Revises: 036401757a87
Create Date: 2026-02-10 14:34:22.000797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a204d9dca2'
down_revision = '036401757a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='list_visibility'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.Enum('WATCHLIST', 'FAVOURITES', name='list_type'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'list_type', name='uq_user_list_type'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_list_name')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_list_type'), ['list_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lists_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_lists_list_type'))

    op.drop_table('lists')
    # ### end Alembic commands ###
