"""empty message

Revision ID: d8caddedcbf0
Revises: 0b8cee4d2a90
Create Date: 2026-02-13 03:17:31.786202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8caddedcbf0'
down_revision = '0b8cee4d2a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'movie_id', name='uq_list_movie')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_items_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_items_movie_id'))
        batch_op.drop_index(batch_op.f('ix_list_items_list_id'))

    op.drop_table('list_items')
    # ### end Alembic commands ###
