"""List unique constraint changed

Revision ID: 0b8cee4d2a90
Revises: b1a204d9dca2
Create Date: 2026-02-11 22:40:26.785808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8cee4d2a90'
down_revision = 'b1a204d9dca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.alter_column('list_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_user_list_type'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_list_type'), ['user_id', 'list_type'])
        batch_op.alter_column('list_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
